PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, google_sub TEXT UNIQUE, email TEXT, name TEXT NOT NULL, picture TEXT, guest INTEGER NOT NULL DEFAULT 0 CHECK(guest IN (0,1)), admin INTEGER NOT NULL DEFAULT 0 CHECK(admin IN (0,1)), age_range TEXT NOT NULL DEFAULT 'general', age_verified INTEGER NOT NULL DEFAULT 1 CHECK(age_verified IN (0,1)));
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS session_expiry ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS worlds (id TEXT PRIMARY KEY, owner_id TEXT REFERENCES users(id), published INTEGER NOT NULL DEFAULT 0 CHECK(published IN (0,1)), data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS scenarios (id TEXT PRIMARY KEY, world_id TEXT REFERENCES worlds(id), owner_id TEXT REFERENCES users(id), data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS characters (id TEXT PRIMARY KEY, owner_id TEXT REFERENCES users(id), world_id TEXT REFERENCES worlds(id), scenario_id TEXT REFERENCES scenarios(id), published INTEGER NOT NULL DEFAULT 0 CHECK(published IN (0,1)), visibility TEXT NOT NULL DEFAULT 'private' CHECK(visibility IN ('private','public','friends','selected')), data TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS character_public_visibility ON characters(published, id DESC);
CREATE INDEX IF NOT EXISTS world_public_visibility ON worlds(published, id DESC);
CREATE TABLE IF NOT EXISTS friendships (user_a TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, user_b TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, requested_by TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, status TEXT NOT NULL CHECK(status IN ('pending','accepted')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(user_a,user_b), CHECK(user_a < user_b), CHECK(requested_by=user_a OR requested_by=user_b));
CREATE INDEX IF NOT EXISTS friendship_user_b ON friendships(user_b,status);
CREATE TABLE IF NOT EXISTS character_shares (character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, PRIMARY KEY(character_id,user_id));
CREATE INDEX IF NOT EXISTS character_shares_user ON character_shares(user_id,character_id);
CREATE TABLE IF NOT EXISTS world_characters (world_id TEXT NOT NULL REFERENCES worlds(id) ON DELETE CASCADE, character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE, PRIMARY KEY(world_id, character_id));
CREATE TABLE IF NOT EXISTS personas (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), world_id TEXT REFERENCES worlds(id), data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), world_id TEXT REFERENCES worlds(id), persona_id TEXT REFERENCES personas(id), scenario_id TEXT REFERENCES scenarios(id), name TEXT NOT NULL, state TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS scenes (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL UNIQUE REFERENCES conversations(id) ON DELETE CASCADE, location TEXT NOT NULL DEFAULT 'An open beginning');
CREATE TABLE IF NOT EXISTS scene_characters (scene_id TEXT NOT NULL REFERENCES scenes(id) ON DELETE CASCADE, character_id TEXT NOT NULL REFERENCES characters(id), PRIMARY KEY(scene_id, character_id));
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, role TEXT NOT NULL CHECK(role IN ('user','assistant','director')), character_id TEXT REFERENCES characters(id), content TEXT NOT NULL, emotion TEXT NOT NULL DEFAULT 'idle', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS memories (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, world_id TEXT REFERENCES worlds(id), persona_id TEXT REFERENCES personas(id), character_id TEXT REFERENCES characters(id), type TEXT NOT NULL, content TEXT NOT NULL, importance REAL NOT NULL, confidence REAL NOT NULL, known_by TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS memory_scope ON memories(owner_id, world_id, persona_id, character_id);
CREATE INDEX IF NOT EXISTS message_conversation ON messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS conversation_owner_updated ON conversations(owner_id, updated_at);
CREATE TABLE IF NOT EXISTS relationships (owner_id TEXT NOT NULL REFERENCES users(id), scope TEXT NOT NULL, character_id TEXT NOT NULL REFERENCES characters(id), affinity INTEGER NOT NULL DEFAULT 0, trust INTEGER NOT NULL DEFAULT 0, familiarity INTEGER NOT NULL DEFAULT 0, mood TEXT NOT NULL DEFAULT 'idle', note TEXT NOT NULL DEFAULT '', PRIMARY KEY(owner_id, scope, character_id));
CREATE TABLE IF NOT EXISTS turn_locks (conversation_id TEXT PRIMARY KEY REFERENCES conversations(id) ON DELETE CASCADE, token TEXT NOT NULL, expires_at INTEGER NOT NULL);
