'use client';
import Link from 'next/link';
import {ArrowRight,ChevronRight,Plus,Sparkles} from 'lucide-react';
import type {Character,World} from '@/lib/types';
import type {CSSProperties,ReactNode} from 'react';
export async function api<T>(path:string,method='GET',data?:unknown):Promise<T>{const r=await fetch(`/api/${path}`,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined,cache:'no-store'});let result;try{result=await r.json();}catch{throw new Error('The server is unavailable. Please try again.');}if(!r.ok)throw new Error(result.error||'Unable to complete this action.');return result;}
export function Portrait({avatar='0',className='',name=''}:{avatar?:string;className?:string;name?:string}){const style:CSSProperties=avatar.startsWith('data:')?{backgroundImage:`url("${avatar}")`,backgroundSize:'cover',backgroundPosition:'center'}:{backgroundPosition:`${Number(avatar)*25}% center`};return <span role={name?'img':undefined} aria-label={name||undefined} aria-hidden={!name} className={`portrait ${className}`} style={style}/>;}
export function SectionTitle({children,href,label='View all'}:{children:ReactNode;href?:string;label?:string}){return <div className="section-title"><h2>{children}</h2>{href&&<Link href={href}>{label}<ChevronRight size={16}/></Link>}</div>;}
export function CharacterCard({character:c}:{character:Character}){return <Link href={`/characters/${c.id}`} className="character-card"><Portrait avatar={c.avatar} name={c.name}/><span className="card-badge">{c.world_id?'World character':'Standalone'}</span><div className="character-caption"><div><h3>{c.name}</h3><div className="tags">{c.tags.slice(0,2).map(t=><span key={t}>{t}</span>)}</div></div><span className="round-arrow"><ArrowRight size={17}/></span></div></Link>;}
export function WorldCard({world:w}:{world:World}){return <Link href={`/worlds/${w.id}`} className={`world-card world-${w.cover}`}><span className="card-badge">{w.owner_id?'Your world':'Original world'}</span><div><small>{w.genre}</small><h3>{w.name}</h3><p>{w.description}</p></div><span className="round-arrow"><ArrowRight size={17}/></span></Link>;}
export function Empty({title,children,href,label}:{title:string;children:ReactNode;href?:string;label?:string}){return <div className="empty"><Sparkles size={26}/><h3>{title}</h3><p>{children}</p>{href&&<Link className="button" href={href}><Plus size={16}/>{label}</Link>}</div>;}
export function ErrorNote({message}:{message:string}){return message?<p className="error-note" role="alert">{message}</p>:null;}
export function PageTitle({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:ReactNode}){return <div className="page-title"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{children}</div>;}
