ALTER TABLE sekaira.relationships
  ADD COLUMN IF NOT EXISTS affinity BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS familiarity BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mood TEXT NOT NULL DEFAULT 'idle';
