CREATE SCHEMA IF NOT EXISTS sekaira;
SET search_path TO sekaira;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, google_sub TEXT UNIQUE, name TEXT NOT NULL, guest BIGINT NOT NULL DEFAULT 0, rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at BIGINT NOT NULL, rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS worlds (id TEXT PRIMARY KEY, owner_id TEXT REFERENCES users(id), data TEXT NOT NULL, rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS scenarios (id TEXT PRIMARY KEY, world_id TEXT REFERENCES worlds(id), owner_id TEXT REFERENCES users(id), data TEXT NOT NULL, rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS avatars (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), type TEXT NOT NULL CHECK(type IN ('image','vrm','live2d')), asset_url TEXT NOT NULL, rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS characters (id TEXT PRIMARY KEY, owner_id TEXT REFERENCES users(id), world_id TEXT REFERENCES worlds(id), scenario_id TEXT REFERENCES scenarios(id), avatar_id TEXT REFERENCES avatars(id), data TEXT NOT NULL, rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS world_characters (world_id TEXT NOT NULL REFERENCES worlds(id) ON DELETE CASCADE, character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE, PRIMARY KEY(world_id, character_id), rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS personas (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), world_id TEXT REFERENCES worlds(id), data TEXT NOT NULL, rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), world_id TEXT REFERENCES worlds(id), persona_id TEXT REFERENCES personas(id), scenario_id TEXT REFERENCES scenarios(id), name TEXT NOT NULL, state TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS scenes (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL UNIQUE REFERENCES conversations(id) ON DELETE CASCADE, location TEXT NOT NULL DEFAULT 'An open beginning', rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS scene_characters (scene_id TEXT NOT NULL REFERENCES scenes(id) ON DELETE CASCADE, character_id TEXT NOT NULL REFERENCES characters(id), PRIMARY KEY(scene_id, character_id), rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, role TEXT NOT NULL CHECK(role IN ('user','assistant','director')), character_id TEXT REFERENCES characters(id), content TEXT NOT NULL, emotion TEXT NOT NULL DEFAULT 'idle', created_at TEXT NOT NULL, rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS memories (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, world_id TEXT REFERENCES worlds(id), persona_id TEXT REFERENCES personas(id), character_id TEXT REFERENCES characters(id), type TEXT NOT NULL, content TEXT NOT NULL, importance REAL NOT NULL, confidence REAL NOT NULL, known_by TEXT NOT NULL, created_at TEXT NOT NULL, rowid BIGSERIAL);
CREATE INDEX IF NOT EXISTS memory_scope ON memories(owner_id, world_id, persona_id, character_id);
CREATE INDEX IF NOT EXISTS message_conversation ON messages(conversation_id, created_at);
CREATE TABLE IF NOT EXISTS relationships (owner_id TEXT NOT NULL REFERENCES users(id), scope TEXT NOT NULL, character_id TEXT NOT NULL REFERENCES characters(id), trust BIGINT NOT NULL DEFAULT 0, note TEXT NOT NULL DEFAULT '', PRIMARY KEY(owner_id, scope, character_id), rowid BIGSERIAL);
CREATE TABLE IF NOT EXISTS turn_locks (conversation_id TEXT PRIMARY KEY REFERENCES conversations(id) ON DELETE CASCADE, token TEXT NOT NULL, expires_at BIGINT NOT NULL, rowid BIGSERIAL);
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE worlds ENABLE ROW LEVEL SECURITY;
ALTER TABLE scenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE avatars ENABLE ROW LEVEL SECURITY;
ALTER TABLE characters ENABLE ROW LEVEL SECURITY;
ALTER TABLE world_characters ENABLE ROW LEVEL SECURITY;
ALTER TABLE personas ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE scenes ENABLE ROW LEVEL SECURITY;
ALTER TABLE scene_characters ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE turn_locks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON SCHEMA sekaira FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA sekaira FROM PUBLIC, anon, authenticated;
